version: '3.4'

services:
  softplan.api1:
    environment:     
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"
    networks:
      - softplan-network

  softplan.api2:
    environment:    
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
    ports:
      - "5002:5002"
    networks:
      - softplan-network

networks:
  softplan-network:
    driver: bridge